apiVersion: v1
kind: Service
metadata:
        name: frontend
spec:
        selector:
                app: microservices
                tier: frontend
        ports:
              - protocol: "TCP"
                port: 80
                targetPort: 80
        type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: users
        labels:
                app: microservices
spec:
        replicas: 1
        template:
                metadata:
                        labels:
                                app: microservices
                                tier: frontend
                spec:
                         containers:
                              - name: microservices-app
                                image: gcr.io/test2-231205/users
                                ports:
                                      - name: users
                                        containerPort: 80
                                env:
                                      - name: GET_HOSTS_FROM
                                        value: env
---
apiVersion: v1
kind: Service
metadata:
        name: bookings-service
spec:
        selector:
                app: microservices
                tier: worker
        ports:
              - port: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: bookings
        labels:
                app: microservices
spec:
        replicas: 1
        template:
                metadata:
                        labels:
                                app: microservices
                                tier: worker
                spec:
                        containers:
                              - name: microservices-app
                                image: gcr.io/test2-231205/bookings
                                ports:
                                      - name: bookings
                                        containerPort: 80
                                env:
                                      - name: GET_HOSTS_FROM
                                        value: env
---
apiVersion: v1
kind: Service
metadata:
        name: movies-service
spec:
        selector:
                app: microservices
                tier: worker
        ports:
              - port: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: movies
        labels:
                app: microservices
spec:
        replicas: 1
        template:
                metadata:
                        labels:
                                app: microservices
                                tier: worker
                spec:
                        containers:
                              - name: microservices-app
                                image: gcr.io/test2-231205/movies
                                ports:
                                      - name: movies
                                        containerPort: 80
                                env:
                                      - name: GET_HOSTS_FROM
                                        value: env
---
apiVersion: v1
kind: Service
metadata:
        name: showtimes-service
spec:
        selector:
                app: microservices
                tier: worker
        ports:
              - port: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
        name: showtimes
        labels:
                app: microservices
spec:
        replicas: 1
        template:
                metadata:
                        labels:
                                app: microservices
                                tier: worker
                spec:
                        containers:
                              - name: microservices-app
                                image: gcr.io/test2-231205/showtimes
                                ports:
                                      - name: showtimes
                                        containerPort: 80
                                env:
                                      - name: GET_HOSTS_FROM
                                        value: env
